export { default as Header } from "./header/Header";
export { default as Hero } from "./hero/Hero";
export { default as Marque } from "./marque/Marque";
export { default as About } from "./about/About";
export { default as Service } from "./service/service";
export { default as Skills } from "./skills/Skills";
export { default as Project } from "./project/Project";
export { default as Contact } from "./contact/Contact";
export { default as Footer } from "./footer/Footer";
