import { useState, useEffect } from "react";
import Head from "next/head";
import {
  Header,
  Contact,
  Footer,
  Hero,
  Marque,
  Project,
  Skills,
} from "@/components";

export default function Home() {
  const [scrollPosition, setScrollPosition] = useState(0);
  useEffect(() => {
    function handleScroll() {
      setScrollPosition(window.scrollY);
    }
    window.addEventListener("scroll", handleScroll);

    // Cleanup the event listener
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  console.log(scrollPosition);

  return (
    <div className="bg-grey blurredBg">
      <div
        className={`animated_header ${
          scrollPosition >= 200 ? "show_header" : ""
        }`}
      >
        <Header />
      </div>
      <Head>
        <title>Sakil Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="page-content relative bg-grey bg-opacity-95 backdrop-blur-lg backdrop-filter">
        <Header />

        <Hero />
        <Marque />
        <Skills />
        <Project />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
